CRUD construcao do modelo
selerao/api-repo pull request #7
Opened 2022-12-21 17:50 UTC by selerao

???

2022-12-21 18:36 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/CategoriasExcala.java
> +public class CategoriasExcala {
```suggestion
Categoria
```

2022-12-21 18:38 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/CategoriasExcala.java
> +@Table(name = "categorias_excala")
```suggestion
@Table(name = "categorias")
```

2022-12-21 18:42 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/CategoriasExcala.java
> +    private String franqueado;
o conceito dessas colunas estão "erradas", na verdade vc precisa de um campo apenas que seria o nome.

tirar essas colunas e colocar apenas o nome.

```suggestion
    @Column(name = "nome", length = 250)
    private String nome;
```

2022-12-21 18:43 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/CategoriasExcala.java
> +
adicionar uma coluna de lista de SubCategoria e usar as anotaçoes oneToMany e ManyToOne

```suggestion
private List<SubCategoria> subcategorias
```

2022-12-21 18:44 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/Funcionarios.java
> +public class Funcionarios {
Tirar o plural em classes

```suggestion
public class Funcionario {
```

2022-12-21 18:45 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/Funcionarios.java
> +    @Column(name = "nome_completo", length = 150)
o length esta errado, no liquibase voce colocou 256, mas aqui apenas 150

2022-12-21 18:46 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/Funcionarios.java
> +    private String categoria;
precisa ser um relacionamento com a Categoria, que voce ja criou e não uma string

```suggestion
    // Usar @ManyToOne e @OneToMany (ja temos exemplo disso)
    private List<Categoria> categorias;
```

2022-12-21 18:49 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/Funcionarios.java
> +    private String cpfFuncionario;
Não precisa colocar funcionario no final porque ja sabemos que é um funcionário
```suggestion
    @Column(name = "cpf")
    private String cpf;
```

2022-12-21 18:50 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/Funcionarios.java
> +    private String cnpjFuncionario;
idem ao comentário acima

2022-12-21 18:50 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/Funcionarios.java
> +    private String pixFuncionario;
idem ao comentário acima

2022-12-21 18:51 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/Funcionarios.java
> +    private String contratoAssinado;
Deve ser do tipo boolean, porque é SIM/NÃO

```suggestion
    private boolean contratoAssinado;
```

2022-12-21 18:51 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/Funcionarios.java
> +    private String responsavelClientesAtivos;
o que significa esse campo?

2022-12-21 18:52 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/Funcionarios.java
> +    private String salario;
Não é melhor salvar o salário do tipo monetário que ja temos alguns exemplos disso no codigo?

2022-12-21 18:54 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/Cliente.java
> +    private String ativo;
ativo tem que ser do tipo boolean (true/false)

```suggestion
    @Column(name = "ativo")
    private boolean ativo;
```

2022-12-21 18:55 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/Cliente.java
> +    private Double precoFixoContrato;
boa, usou valor monetário aqui

2022-12-21 18:57 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/Cliente.java
> +    private String contaAnuncios;
Esse campo precisa de relacionamento com a classe Conta.

```suggestion
    usar many to one e one to many, um cliente pode ter varias contas, mas uma conta ser de um cliente.
    private List<Conta> contas;
```

2022-12-21 19:01 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/Cliente.java
> +    private String contratoAssinado;
aqui acho melhor colocar como valor boolean também

```suggestion
    @Column(name = "contrato_assinado")
    private boolean contratoAssinado;
```

2022-12-21 19:07 UTC, NicolasFujisawa commented on src/main/java/br/com/excaladashboard/models/Produtos.java
> +    private String produto;
o nome dessa variavel correta deveria ser "nome", porque o produto ja é o nome da tabela

2022-12-21 19:16 UTC, NicolasFujisawa requested changes
deixei alguns comentários

2023-01-03 22:35 UTC, selerao commented
da uma olhadar

2023-02-01 22:54 UTC, merged